FORMAT: 1A
HOST: http://onboarding.example.org/

# Onboarding API (HTML Sketch)

Onboarding API for BigCo, Inc

## Home [/]

### Show Home Page [GET]

+ Response 200 (text/html)

        <h1>HOME</h1>
       
        <p><a href="/list">LIST</a></p>

## Onboarding List [/list]

### Show Onboarding Record List [GET]

+ Response 200 (text/html)

        <h1>LIST</h1>

        <p><a href="/create">CREATE-FORM</a></p>
        <p><a href="/12w3e4r5t">ITEM:1q2w3e4r5t</a></p> 

### Create Onboarding Record [POST]

+ Request (application/x-www-form-urlencoded)

            onboardingId=1q2w3e4r5t

+ Response 201 (text/html)

    + Header 
        
            Location: /1q2w3e4r5t

    + Body
    
            <h1>created new onboarding record...</h1>
            <p><a href="/1q2w3e4r5t">ITEM:1q2w3e4r5t</a></p>
            
## Onboarding Create Form [/create]

### Show Onboarding Create Form [GET]
+ Response 200 (text/html)

        <h1>CREATE-FORM</h1>

        <form name="create" action="/list" method="post">
           onboardingId:<input name="onboardingId" value="1q2w3e4r5t" />
           <input type="submit" />
        </form>

# Onboarding Record [/1q2w3e4r5t]

### Show Onboarding Record [GET]

+ Response 200 (text/html)

        ITEM:1q2w3e4r5t

## Add Company Info [/1q2w3e4r5t/company]

### Show Company Info Form [GET]

+ Response 200 (text/html)

        COMPANY-INFO-FORM

## Add Account Info [/1q2w3e4r5t/account]

### Show Account Info Form [GET]

+ Response 200 (text/html)

        ACCOUNT-INFO-FORM

## Add Activity Info [/1q2w3e4r5t/activity]

### Show Activity Info Form [GET]

+ Response 200 (text/html)

        ACTIVITY-INFO-FORM

## Approve Onboarding [/1q2w3e4r5t/approve]

### Show Approve Form [GET]

+ Response 200 (text/html)

        APPROVE-ONBOARDING-FORM
        
## Reject Onboarding [/1q2w3e4r5t/reject]

### Show Reject Form [GET]

+ Response 200 (text/html)

        REJECT-ONBOARDING-FORM

